spring:
  application:
    name: SpringAICode
  config:
    import: optional:application-secrets.yaml
  ai:
    openai:
      embedding:
        options:
          model: text-embedding-ada-002
  datasource:
    url: jdbc:postgresql://localhost:5433/vector_store
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      schema-locations: classpath:init/schema.sql
      mode: always



server:
  port: 8088
