services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: vector_store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "5433:5432"
