spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888

#  mongodb:
#    username: admin
#    password: admin
#    host: localhost
#    port: 27017
#    database: customer
#    authentication-database: admin
#
#server:
#  port: 8090
